title: WVTRA
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Creating a more neighbourly village and a safe, beautiful place to live.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.walbottlevillagetra.co.uk/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
author: Walbottle Village Tenants &amp; Residents Association Website

# Build settings
permalink: /:categories/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache 
  - jekyll-minifier
  - jekyll-last-modified-at

defaults:
  description: Creating a more neighbourly village and a safe, beautiful place to live.

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  

include:
  - _pages

markdown: kramdown


permalink: pretty

exclude: [README.md]
